export { default as Text } from '@components/common/text/Text'
export { default as H1 } from '@components/common/text/H1'
export { default as H2 } from '@components/common/text/H2'
export { default as H3 } from '@components/common/text/H3'
export { default as H4 } from '@components/common/text/H4'
export { default as H5 } from '@components/common/text/H5'
